b50:
  bg: b50_bg.png
  coverWidth: 180
  coverRatio: 1.7777777777777777
  oldCols: 5
  newCols: 5
  gapX: 10
  gapY: 26
  pos:
    name:
      fontName: Source Han Sans CN Bold Bold
      size: 30
      x: 192
      y: 132
      scale: 1.0
    dxrating:
      fontName: Arial Black
      size: 15
      x: 326
      y: 80
      scale: 1.0
    chTitle:
      fontName: Source Han Sans CN Bold Bold
      size: 16
      x: 10
      y: 32
      scale: 1.0
    chAchievements:
      fontName: Source Han Sans CN Bold Bold
      size: 18
      x: 10
      y: 74
      scale: 1.0
    chBase:
      fontName: Source Han Sans CN Bold Bold
      size: 12
      x: 10
      y: 92
      scale: 1.0
    label:
      fontName: ''
      size: 0
      x: 0
      y: -10
      scale: 1.0
    rateIcon:
      fontName: ''
      size: 0
      x: 100
      y: 38
      scale: 1.0
    fcIcon:
      fontName: ''
      size: 0
      x: 123
      y: 72
      scale: 0.56
    fsIcon:
      fontName: ''
      size: 0
      x: 145
      y: 72
      scale: 0.56
    type:
      fontName: ''
      size: 0
      x: 110
      y: -10
      scale: 1.0
    shadow:
      fontName: ''
      size: 0
      x: 0
      y: 2
      scale: 1.0
    oldCharts:
      fontName: ''
      size: 0
      x: 61
      y: 233
      scale: 1.0
    newCharts:
      fontName: ''
      size: 0
      x: 61
      y: 1150
      scale: 1.0
    ratingBg:
      fontName: ''
      size: 0
      x: 182
      y: 54
      scale: 1.0
    dani:
      fontName: ''
      size: 0
      x: 358
      y: 54
      scale: 0.58
scoreList:
  bg: score_bg.png
  coverWidth: 180
  coverRatio: 1.7777777777777777
  oldCols: 5
  newCols: 5
  gapX: 10
  gapY: 26
  pos:
    name:
      fontName: Source Han Sans CN Bold Bold
      size: 30
      x: 192
      y: 132
      scale: 1.0
    dxrating:
      fontName: Arial Black
      size: 15
      x: 326
      y: 80
      scale: 1.0
    chTitle:
      fontName: Source Han Sans CN Bold Bold
      size: 16
      x: 10
      y: 32
      scale: 1.0
    chAchievements:
      fontName: Source Han Sans CN Bold Bold
      size: 18
      x: 10
      y: 74
      scale: 1.0
    chBase:
      fontName: Source Han Sans CN Bold Bold
      size: 12
      x: 10
      y: 92
      scale: 1.0
    info:
      fontName: Source Han Sans CN Bold Bold
      size: 24
      x: 360
      y: 218
      scale: 1.0
    label:
      fontName: ''
      size: 0
      x: 0
      y: -10
      scale: 1.0
    rateIcon:
      fontName: ''
      size: 0
      x: 100
      y: 38
      scale: 1.0
    fcIcon:
      fontName: ''
      size: 0
      x: 123
      y: 72
      scale: 0.56
    fsIcon:
      fontName: ''
      size: 0
      x: 145
      y: 72
      scale: 0.56
    type:
      fontName: ''
      size: 0
      x: 110
      y: -10
      scale: 1.0
    shadow:
      fontName: ''
      size: 0
      x: 0
      y: 2
      scale: 1.0
    oldCharts:
      fontName: ''
      size: 0
      x: 61
      y: 260
      scale: 1.0
    ratingBg:
      fontName: ''
      size: 0
      x: 182
      y: 54
      scale: 1.0
    dani:
      fontName: ''
      size: 0
      x: 358
      y: 54
      scale: 0.58
dsList:
  bg: ds_bg.png
  coverWidth: 70
  coverRatio: 1.0
  oldCols: 10
  newCols: 0
  gapX: 12
  gapY: 12
  pos:
    title:
      fontName: Source Han Sans CN Bold Bold
      size: 50
      x: 535
      y: 145
      scale: 1.0
    ds:
      fontName: Source Han Sans CN Bold Bold
      size: 48
      x: -140
      y: 55
      scale: 1.0
    list:
      fontName: ''
      size: 0
      scale: 1.0
      x: 170
      y: 230
    rateIcon:
      fontName: ''
      size: 0
      scale: 0.86
      x: 0
      y: 20
    fcIcon:
      fontName: ''
      size: 0
      scale: 1.0
      x: 12
      y: 10
info:
  bg: info.png
  coverWidth: 200
  coverRatio: 1.0
  oldCols: 5
  newCols: 0
  gapX: 96
  gapY: 96
  pos:
    cover:
      fontName: ''
      size: 200
      scale: 1.0
      x: 120
      y: 155
    title:
      fontName: Source Han Sans CN Bold Bold
      size: 36
      scale: 1.0
      x: 344
      y: 185
    artist:
      fontName: Source Han Sans CN Bold Bold
      size: 24
      scale: 1.0
      x: 344
      y: 224
    details:
      fontName: Source Han Sans CN Bold Bold
      size: 24
      scale: 1.0
      x: 344
      y: 350
    list:
      fontName: ''
      size: 0
      scale: 1.0
      x: 261
      y: 435
    diffInfo:
      fontName: Source Han Sans CN Bold Bold
      size: 24
      scale: 1.0
      x: 20
      y: 30
    ds:
      fontName: Source Han Sans CN Bold Bold
      size: 24
      scale: 1.0
      x: 650
      y: 30
    rateIcon:
      fontName: ''
      size: 0
      scale: 1.143
      x: 180
      y: 2
    fcIcon:
      fontName: ''
      size: 0
      scale: 1.0
      x: 300
      y: -3
    fsIcon:
      fontName: ''
      size: 0
      scale: 1.0
      x: 350
      y: -3
    genre:
      fontName: ''
      size: 0
      scale: 0.55
      x: 802
      y: 280